Install Google Cloud SDK in the driver image (#341)
* Install Google Cloud SDK in the driver image

* Add curl

* Remove gcloud components install beta

Apparently that's not necessary when using apt-get:
  ERROR: (gcloud.components.install)
  You cannot perform this action because the Google Cloud CLI component manager
  is disabled for this installation. You can run the following command
  to achieve the same result for this installation:

  sudo apt-get install google-cloud-sdk

* Restore indentation